### ISSUE TITLE
Plants are not growing.

### ISSUE THREAD

**Issue by rickyc** [ableco/planter#2]
Hello Mister Lim (@blim8183),

I've tried to 💧 the 🌱 , but they won't grow into 🌷s or 🌲 s. I think I've sown the seeds properly. Maybe the 🐔 or 🐿  has gotten to them? It's been 🌦  lately, so I think it has enough🚰 . Can you help?

- 😕

**Comment by blim8183** [comment]
Sorry, this was a problem with poor documentation. I've addressed the issue with this commit: https://github.com/ableco/planter/commit/ab9388d98275c1545e0a7507852fc93a3c490ed2

**Comment by rickyc** [comment]
Thank you kind sir. I will check to see if the 🌱 will grow into a 🌻 and report back.

**Comment by blim8183** [comment]
Fare thee well. May your roots be strong and your leaves forever green. 👋
